// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vagrjonewjbjeuotsrya.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZhZ3Jqb25ld2piamV1b3RzcnlhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY4ODA0MzgsImV4cCI6MjA3MjQ1NjQzOH0.I8yQhk7JSSol3EeVtMs2ZmVVj3Y1TndyLNUsjHf8H-0";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});